{ config, pkgs, ... }:

let
  # Placeholder for future variables or configurations
in
{
  # Import hardware configuration generated by NixOS
  imports = [
    ./hardware-configuration.nix
  ];

  # Hardware configuration
  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
    };

    # NVIDIA-specific settings
    nvidia = {
      modesetting.enable = true;

      powerManagement = {
        enable = false;
        finegrained = false;
      };

      open = false;  # Use the proprietary NVIDIA driver
      nvidiaSettings = true; # Enable NVIDIA settings tool
      package = config.boot.kernelPackages.nvidiaPackages.beta; # Use beta NVIDIA driver
    };
  };

  # Services configuration
  services = {
    xserver = {
      enable = true;

      # Keyboard layout configuration
      xkb = {
        layout = "us";
        variant = "";
      };

      videoDrivers = [ "nvidia" ];

      # Enable GNOME desktop environment with GDM display manager
      displayManager.gdm.enable = true;
      desktopManager.gnome.enable = true;
    };
  };

  # Enable Steam
  programs.steam.enable = true;

  # Install system packages
  environment.systemPackages = with pkgs; [
    gnomeExtensions.forge
  ];
}
